/*
 * generated by Xtext
 */
package com.typesafe.config;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class HoconStandaloneSetup extends HoconStandaloneSetupGenerated{

	public static void doSetup() {
		new HoconStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

