/*
 * generated by Xtext
 */
package com.typesafe.config;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class HoconRuntimeModule extends com.typesafe.config.AbstractHoconRuntimeModule {

}
