/*
 * generated by Xtext
 */
package com.typesafe.config.ui.contentassist

import com.typesafe.config.ui.contentassist.AbstractHoconProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class HoconProposalProvider extends AbstractHoconProposalProvider {
}
