/*
 * generated by Xtext
 */
package com.typesafe.config.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class HoconUiModule extends com.typesafe.config.ui.AbstractHoconUiModule {
	public HoconUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
